name: Build PriceIt Auth & Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      NODE_ENV: ${{ secrets.NODE_ENV }}
      local_port: ${{ secrets.LOCAL_SERVER_PORT }}
      PORT: ${{ secrets.PORT }}
      dbUserName: ${{ secrets.MONGO_USERNAME }}
      dbName: ${{ secrets.MONGO_DATABASE_NAME }}
      dbPass: ${{ secrets.MONGO_PASSWORD }}
      dbHost: ${{ secrets.MONGO_HOST }}
      dbPort: ${{ secrets.MONGO_PORT }}
      redisPort: ${{ secrets.REDIS_URL }}
      accessTokenPrivateKey: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}


    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        
    - name: Install Node Dependencies
      run: npm install
      
    - name: Create empty .env file (required by docker-compose)
      run: touch .env
      
    - name: Start containers
      run: docker-compose up -d --build
      
    - name: Wait for containers to start
      run: sleep 20s

#    - name: Run Unit Tests
#      run: npm test
      
    - name: Stop containers and remove volumes
      run: docker-compose down -v
